//
//  FabulousActionViews.swift
//  Fabulous
//
//  Created by Ryan Wachowski on 7/5/18.
//  Copyright © 2018 Duet Health LLC. All rights reserved.
//

import Foundation
import UIKit

/// Encapsulates the views backed by a `FabulousAction` to allow for customization of those views.
///
/// If the views generated by the fab for your custom action require further customization, you may
/// do so by accessing the properties of this class.
@objc public class FabulousActionViews: NSObject {

    /// The touch target for the action.
    public let button: UIButton

    /// The title label for the action. If the action has no title, this property is nil.
    public let label: UILabel?

    init(_ button: UIButton, _ label: UILabel? = nil) {
        self.button = button
        self.label = label
    }

}
